POST http://localhost:3001/automatons/add-automaton
content-type: application/json

{
   "username":"402390142",
   "newAutomaton":{
      "automatonName":"automataFA",
      "nodes":[
         {
            "id":1,
            "label":"S0",
            "final":false,
            "start":true
         },
         {
            "id":2,
            "label":"S1",
            "final":true,
            "start":false
         },
         {
            "id":3,
            "label":"S2",
            "final":true,
            "start":false
         },
         {
            "id":4,
            "label":"S3",
            "final":false,
            "start":false
         },
         {
            "id":5,
            "label":"S4",
            "final":false,
            "start":false
         },
         {
            "id":6,
            "label":"S4",
            "final":false,
            "start":false
         },
         {
            "id":7,
            "label":"S4",
            "final":false,
            "start":false
         }
      ],
      "edges":[
         {
            "from":1,
            "to":1,
            "label":"0"
         },
         {
            "from":1,
            "to":2,
            "label":"1"
         },
         {
            "from":2,
            "to":3,
            "label":"1"
         },
         {
            "from":2,
            "to":4,
            "label":"0"
         }
      ]
   }
}